### ISSUE TITLE
Simpler Types

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [cspotcode/single-event-emitter#1]
Right now it seems like there can only be up to 4 arguments, and the type definitions look very messy:

```ts
export type EmitSpec =
  [0] |
  [0, () => void] |
  [0, () => void, any] |
  [1] |
  [1, (a: any) => void] |
  [1, (a: any) => void, any] |
  [2] |
  [2, (a: any, b: any) => void] |
  [2, (a: any, b: any) => void, any] |
  [3] |
  [3, (a: any, b: any, c: any) => void] |
  [3, (a: any, b: any, c: any) => void, any] |
  [4] |
  [4, (a: any, b: any, c: any, d: any) => void] |
  [4, (a: any, b: any, c: any, d: any) => void, any] |
  [-1] |
  [-1, (...args: any[]) => void] |
  [-1, (...args: any[]) => void, any];
```

- [x] I can try making it so that the types are simpler and more flexible with the arguments and make a PR for it

**Comment by cspotcode** [comment]
Sure, go for it.  I think this library predates newer TypeScript features that make this cleaner.

**Comment by ChocolateLoverRaj** [comment]
What branch should I base my PR off of? It seems like the default branch has [different types](https://github.com/cspotcode/single-event-emitter/blob/c76edbbbb39f6a8d0e4349efb1afbcbf29ad0a7d/index.d.ts#L5) than the [ones published to npm](https://cdn.jsdelivr.net/npm/single-event-emitter@0.2.0/index.d.ts).

**Comment by cspotcode** [comment]
I'm not sure.  I'll see if I can find my local clone somewhere and push from there.

**Comment by cspotcode** [comment]
I found my old code.  I pushed a single new commit with some TODO notes in the README: https://github.com/cspotcode/single-event-emitter/commit/7f957ff4ec2869b4af33e00a81bfaf05068fe961

I am not sure if they are important.  Feel free to remove them in your pull request if you want.
I updated the repository so that the default branch is `main`.  It has the latest 0.2.0 code.
